### ISSUE TITLE
Add checklist for Incantations

### ISSUE THREAD

**Issue by wdya** [Roundtable-Hold/tracker#39]

**Comment by thomasgraham18** [comment]
- [ ] Bestial Incantations

- [ ] Blood Incantations

- [ ] Dragon Communion Incantations

- [ ] Dragon Cult Incantations

- [ ] Erdtree Incantations

- [ ] Fire Giant Incantations

- [ ] Fire Monk Incantations

- [ ] Frenzied Flame Incantations

- [ ] Godksin Apostle Incantations

- [ ] Golden Order Incantations

- [ ] Servant of Rot Incantations

- [ ] Two Fingers Incantations
